export enum VaultedShopperErrors {
    VALIDATION_GENERAL_FAILURE = 'VALIDATION_GENERAL_FAILURE',
    MISSING_VAULTED_SHOPPER_FIELDS = 'MISSING_VAULTED_SHOPPER_FIELDS',
    MISSING_RELEVANT_METHOD_FOR_SHOPPER = 'MISSING_RELEVANT_METHOD_FOR_SHOPPER'
}
